#CONSTANTE FOLOSITE PE PARCURSUL CODULUI

#PCA
ADDR_PCA=0x40
FREQ_PCA=50
MIN_PCA=500
MAX_PCA=2500
channelGrip=0 #gripperServo pe PCA
channelPitch=1 #pitchServo pe PCA

#MOTOR DRIVER
COMPENSATION_LEFT=0.4
COMPENSATION_RIGHT=0.4
CHIP=0
PWM_FREQ_HZ=20_000
PWM_PERIOD_NS = int (1e9 // PWM_FREQ_HZ)
ENA=12
ENB=13
IN1=23
IN2=24
IN3=5
IN4=6

#HARDWARE PWM
PWM_PATH = "/sys/class/pwm/pwmchip0"
PWM0 = f"{PWM_PATH}/pwm0"   # GPIO12 -> ENA
PWM1 = f"{PWM_PATH}/pwm1"   # GPIO13 -> ENB

#TODO:SENZOR HUM SI TEMP
